version: '3'
services:

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
  tests:
    image: tests_image
    container_name: tests
    depends_on: [selenium]
    build:
      context: .
