name: Run Immortal UI tests Docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Daily schedule at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Downloads This Repo
        uses: actions/checkout@v2

      - name: Change wrapper permissions # Adds this pernission to be able to run Gradle Commands
        run: chmod +x ./gradlew

      - name: Run Immortal UI tests Inside Docker  # Runs docker-compose.yml file from current repo
        run: |
          docker-compose up -d
      - name: Wait Until Tests Passed  # Runs docker-compose.yml file from current repo
        run: |
          docker wait tests_container
      - name: Close Containers  # Runs docker-compose.yml file from current repo
        run: |
          docker-compose down