name: Run Immortal UI tests Docker

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Daily schedule at midnight UTC

env:
  TEST_EXIT_CODE: 0


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Downloads This Repo
        uses: actions/checkout@v2

      - name: Change wrapper permissions # Adds this pernission to be able to run Gradle Commands
        run: chmod +x ./gradlew

      - name: Run Immortal UI tests Inside Docker
        id: tests
        run: |
          docker-compose up tests
          exit_code=$(docker inspect -f '{{.State.ExitCode}}' tests)
          echo $exit_code
          if [ $exit_code -eq 0 ]; then
          echo "Tests passed!"
          echo "Setting a 0 value" 
          TEST_EXIT_CODE=0
          else
          echo "Tests failed!"
          echo "Setting a 1 value"
          TEST_EXIT_CODE=1
          fi

      - name: Close Containers
        run: docker-compose down

  slackNotification: # Approach is used from here https://github.com/marketplace/actions/slack-notify
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Send Slack Notification
        run:  |
          echo $TEST_EXIT_CODE
          if [ $TEST_EXIT_CODE -eq 0 ]; then
            status="Success"
            message="Tests passed! Workflow has completed successfully."
          else
            status="Failure"
            message="Tests failed! Workflow has completed with failures."
          fi