name: Run Immortal UI tests Docker

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Daily schedule at midnight UTC

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Downloads This Repo
        uses: actions/checkout@v2

      - name: Change wrapper permissions # Adds this pernission to be able to run Gradle Commands
        run: chmod +x ./gradlew

      - name: Run Immortal UI tests Inside Docker
        id: tests
        run: |
          docker-compose up tests
          exit_code=$(docker inspect -f '{{.State.ExitCode}}' tests)
          echo $exit_code

      - name: Send Slack Notification
        run: |
          exit_code=$(docker inspect -f '{{.State.ExitCode}}' tests)
          if [ exit_code == 0 ]; then
            status="Success"
            message="Tests passed! Workflow has completed successfully."
          else
            status="Failure"
            message="Tests failed! Workflow has completed with failures."
          fi

      - name: Close Containers
        run: docker-compose down