name: Run Immortal UI tests Docker

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Daily schedule at midnight UTC

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Downloads This Repo
        uses: actions/checkout@v2

      - name: Change wrapper permissions # Adds this pernission to be able to run Gradle Commands
        run: chmod +x ./gradlew

      - name: Run Immortal UI tests Inside Docker  # Runs docker-compose.yml file from current repo
        run: |
          docker-compose up -d
      - name: Wait Until Tests Passed  # Runs docker-compose.yml file from current repo
        run: |
          docker wait tests_container
      - name: Close Containers  # Runs docker-compose.yml file from current repo
        run: |
          docker-compose down

  slackNotification: # Approach is used from here https://github.com/marketplace/actions/slack-notify
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ build.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_USERNAME: ImmortalProdTests
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}